# Generated by Django 5.0.4 on 2024-05-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_prodb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodb',
            old_name='IImage',
            new_name='Image',
        ),
    ]
