# Generated by Django 5.0.5 on 2024-05-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_iimage_prodb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='product images'),
        ),
    ]
