# Generated by Django 5.0.5 on 2024-05-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='Password2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
