# Generated by Django 5.0.5 on 2024-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
