# Generated by Django 5.0.5 on 2024-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
